version: '3.8'

services: 
  app:
    image: mwoodpatrick/wp-codespace:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    container_name: devcontainer-wp
    hostname: devcontainer-wp

  db:
    # https://hub.docker.com/_/mariadb
    image: mariadb:11.1
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      
  phpmyadmin:
    # https://hub.docker.com/_/phpmyadmin
    image: phpmyadmin:5.2
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PMA_HOST: db

volumes:
  mariadb-data:
